# Uncomment the next line to define a global platform for your project
platform :macOS, '10.14'

target 'crackme' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for crackme

  pod 'Arcane'
end
